# Spark Job
apiVersion: batch/v1
kind: Job
metadata:
  name: pyspark-analysis
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: spark
        image: swr.cn-north-4.myhuaweicloud.com/cloud-lab2/cloud_project-pyspark:latest
        command: ["spark-submit", "/opt/spark/work/wordcount.py"]
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Never
